### ISSUE TITLE
README Clarification Embedded Targets

### ISSUE THREAD

**Issue by quicksketch** [edgeimpulse/multi-impulse-deployment-block#2]
I am trying to build a multi-impulse (audio + gesture classification) for an Arduino ESP32 target. The README states:

> For embedded targets, you'll need to change the cross-compiler or integrate the multi-impulse inference library within your application.

I am not sure what either "cross-compiler" or "multi-impulse inference library" refer to here. I have searched for both of these terms in relation to Edge Impulse but have come up short. Could this section either be elaborated upon or provide links to each of these tools?

**Comment by AIWintermuteAI** [comment]
That phrase is really a 10000 ft. view on what you need to build a multi-impulse for embedded target, but since the range of targets is so broad, we can't be more specific.
If you are not sure what is "cross-compiler", it is best to search for some information on that beforehand, the topic of cross-compilation is too broad for us to cover.
Multi-impulse inference library in this case refers to the output result of the deployment block, so what you get in deploy.zip.
